import Head from "next/head";
import { useQuery, gql } from "@apollo/client";

const Home = () => {
  const { loading, error, data } = useQuery(
    gql`
      query ExampleQuery {
        example {
          id
        }
      }
    `
  );

  return (
    <>
      <Head>
        <title>T3 w/ graphql</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <pre className="text-white">
          <h1 className="my-3 text-2xl">T3 app with prisma and graphql</h1>
          <h2 className="text-md mb-2">
            Some example data fetched using graphql:
          </h2>
          <code>{JSON.stringify(error)}</code>
          <code>{JSON.stringify(data, null, 2)}</code>
        </pre>
      </main>
    </>
  );
};

export default Home;
